import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@polaris/ui/globals.css";
import { cn } from "@polaris/ui/cn";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					geistSans.variable,
					geistMono.variable,
					"antialiased whitespace-pre-line overscroll-none",
				)}
			>
				{children}
			</body>
		</html>
	);
}
